name: append car traffic data every 30 min

on:
  workflow_dispatch:
  schedule:
    - cron: '0,30 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: append new car traffic data
      env:
        TINYBIRD_HOST: ${{ secrets.TINYBIRD_HOST }}
        TINYBIRD_TOKEN: ${{ secrets.TINYBIRD_TOKEN }}
      run: bash .github/scripts/fetch_cars_traffic.sh
